### ISSUE TITLE
third party resources to custom resources 

### ISSUE THREAD

**Issue by ghost** [kbst/mongodb#4]
Hi @pst 

Third party resources are deprecated in Kubernetes 1.7, we want to use the mongodb operator on kubernetes 1.7

I am working on a fix right now, looks like it won't be a lot of work.

-Rob

**Comment by pst** [comment]
Hey @rjrhaverkamp,

Thanks for reporting. Currently the operator is in alpha state and I would not recommend to run it in production. Apart from the TPR CRD issue it's also currently not yet scaling clusters yet. And doesn't do backups. But of course any contributions are welcome.

**Comment by pastukhov** [comment]
Hi @pst, @rjrhaverkamp 
Any progress?

**Comment by ghost** [comment]
Hi @pastukhov 

I did some work on this a while ago. I believe I fixed the TPR->CRD issue but never opened a pull request. Because of our timeline we decided to use MongoDB atlas. Though, once we have more time I still hope to move everything into Kubernetes clusters.

**Comment by pst** [comment]
There is a branch, that should mostly work, but I didn't have time yet to get it done. https://github.com/kbst/mongodb/compare/upgrade-to-crds
