### ISSUE TITLE
Repository description refers to Memcached

### ISSUE THREAD

**Issue by scruplelesswizard** [kbst/mongodb#5]
<img width="678" alt="screen shot 2018-02-08 at 15 16 37" src="https://user-images.githubusercontent.com/15822260/35977333-22785338-0ce3-11e8-9c72-619e8522e5d0.png">

Current:

`Memcached Operator for Kubernetes https://www.kubestack.com/catalog/mon…`

Expected:

`Mongodb Operator for Kubernetes https://www.kubestack.com/catalog/mon…`

**Comment by pst** [comment]
Fixed, thanks.
