### ISSUE TITLE
Can't use with newer kubernetes

### ISSUE THREAD

**Issue by montyz** [kbst/mongodb#7]
The “ThirdPartyResource” resource has been deprecated in favor of a “CustomResourceDefinition” resource in Kubernetes 1.7 and has officially been removed in Kubernetes 1.8+.

Deploying this in a new cluster with kubernetes 1.9 I get:

> error: unable to recognize extensions/v1beta1, Kind=ThirdPartyResource: no matches for kind "ThirdPartyResource" in version "extensions/v1beta1"

**Comment by pst** [comment]
The CRD support has been in a branch for some time now and would have required building your own image. I've had it running for a side project for a couple of month but until now didn't get around merging into master. The operator is still far from production ready, but it also didn't lose all my data all the time.

That being said, CRD support is merged into master now #8. And I've also added some happy path integration tests #9 and #10.
